CREATE TABLE `ps_map_data_halflife_dod` (
  `dataid` int unsigned NOT NULL default '0',
  `allieskills` smallint unsigned NOT NULL default '0',
  `axiskills` smallint unsigned NOT NULL default '0',
  `joinedallies` smallint unsigned NOT NULL default '0',
  `joinedaxis` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `allieswon` smallint unsigned NOT NULL default '0',
  `allieslost` smallint unsigned NOT NULL default '0',
  `axiswon` smallint unsigned NOT NULL default '0',
  `axislost` smallint unsigned NOT NULL default '0',
  `bombplanted` smallint unsigned NOT NULL default '0',
  `bombdefused` smallint unsigned NOT NULL default '0',
  `killedbombplanter` smallint unsigned NOT NULL default '0',
  `alliesflagscaptured` smallint unsigned NOT NULL default '0',
  `axisflagscaptured` smallint unsigned NOT NULL default '0',
  `flagscaptured` smallint unsigned NOT NULL default '0',
  `alliesflagsblocked` smallint unsigned NOT NULL default '0',
  `axisflagsblocked` smallint unsigned NOT NULL default '0',
  `flagsblocked` smallint unsigned NOT NULL default '0',
  `alliesscore` smallint unsigned NOT NULL default '0',
  `axisscore` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;
CREATE TABLE `ps_plr_data_halflife_dod` (
  `dataid` int unsigned NOT NULL default '0',
  `allieskills` smallint unsigned NOT NULL default '0',
  `axiskills` smallint unsigned NOT NULL default '0',
  `alliesdeaths` smallint unsigned NOT NULL default '0',
  `axisdeaths` smallint unsigned NOT NULL default '0',
  `joinedallies` smallint unsigned NOT NULL default '0',
  `joinedaxis` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `allieswon` smallint unsigned NOT NULL default '0',
  `allieslost` smallint unsigned NOT NULL default '0',
  `axiswon` smallint unsigned NOT NULL default '0',
  `axislost` smallint unsigned NOT NULL default '0',
  `bombplanted` smallint unsigned NOT NULL default '0',
  `bombdefused` smallint unsigned NOT NULL default '0',
  `killedbombplanter` smallint unsigned NOT NULL default '0',
  `alliesflagscaptured` smallint unsigned NOT NULL default '0',
  `axisflagscaptured` smallint unsigned NOT NULL default '0',
  `flagscaptured` smallint unsigned NOT NULL default '0',
  `alliesflagsblocked` smallint unsigned NOT NULL default '0',
  `axisflagsblocked` smallint unsigned NOT NULL default '0',
  `flagsblocked` smallint unsigned NOT NULL default '0',
  `alliesscore` smallint unsigned NOT NULL default '0',
  `axisscore` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;
CREATE TABLE `ps_plr_maps_halflife_dod` (
  `dataid` int unsigned NOT NULL default '0',
  `allieskills` smallint unsigned NOT NULL default '0',
  `alliesdeaths` smallint unsigned NOT NULL default '0',
  `axiskills` smallint unsigned NOT NULL default '0',
  `axisdeaths` smallint unsigned NOT NULL default '0',
  `joinedallies` smallint unsigned NOT NULL default '0',
  `joinedaxis` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `allieswon` smallint unsigned NOT NULL default '0',
  `allieslost` smallint unsigned NOT NULL default '0',
  `axiswon` smallint unsigned NOT NULL default '0',
  `axislost` smallint unsigned NOT NULL default '0',
  `bombplanted` smallint unsigned NOT NULL default '0',
  `bombdefused` smallint unsigned NOT NULL default '0',
  `killedbombplanter` smallint unsigned NOT NULL default '0',
  `alliesflagscaptured` smallint unsigned NOT NULL default '0',
  `axisflagscaptured` smallint unsigned NOT NULL default '0',
  `flagscaptured` smallint unsigned NOT NULL default '0',
  `alliesflagsblocked` smallint unsigned NOT NULL default '0',
  `axisflagsblocked` smallint unsigned NOT NULL default '0',
  `flagsblocked` smallint unsigned NOT NULL default '0',
  `alliesscore` smallint unsigned NOT NULL default '0',
  `axisscore` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;

-- Moved from defaults.sql.
INSERT INTO `ps_config_events` (`id`, `gametype`, `modtype`, `eventname`, `alias`, `regex`, `idx`, `ignore`, `codefile`) 
    VALUES 
        (1,'halflife','','kill','','/^\"(.+(?:<[^>]*>))\" killed \"(.+(?:<[^>]*>))\" with \"([^\"]*)\"(.*)/',10,0,''),
        (2,'halflife','','attacked','','/^\"(.+(?:<[^>]*>))\" attacked \"(.+(?:<[^>]*>))\" with \"([^\"]+)\"(.*)/',20,1,''),
        (3,'halflife','','plrtrigger','','/^\"(.+(?:<[^>]*>))\" triggered \"([^\"]+)\"(.*)/',30,0,''),
        (4,'halflife','','round','','/^World triggered \"([^\"]+)\"(.*)/',40,0,''),
        (5,'halflife','','entered_game','','/^\"(.+(?:<[^>]*>))\" entered the game(.*)/',50,0,''),
        (6,'halflife','','joined_team','','/^\"(.+(?:<[^>]*>))\" joined team \"([^\"]+)\"/',60,0,''),
        (7,'halflife','','suicide','','/^\"(.+(?:<[^>]*>))\" committed suicide with \"([^\"]+)\"(.*)/',70,0,''),
        (8,'halflife','','changed_name','','/^\"(.+(?:<[^>]*>))\" changed name to \"([^\"]+)\"/',80,0,''),
        (9,'halflife','','connected','','/^\"(.+(?:<[^>]*>))\" connected, address \"([^\"]+)\"/',90,0,''),
        (10,'halflife','','connected_steamid','','/^\"(.+(?:<[^>]*>))\" (?:STEAM|VALVE) USERID (.+)/',100,0,''),
        (11,'halflife','','disconnected','','/^\"(.+(?:<[^>]*>))\" disconnected/',110,0,''),
        (12,'halflife','','chat','','/^\"(.+(?:<[^>]*>))\" say(_team)* \"(.*)\"?(.*)/',120,0,''),
        (13,'halflife','','rcon','','/^(Bad )?Rcon: \"rcon (-*\\d+) \"?(.*?)\"? (.+?)(?:\" from \"([^\"]+)\")?/',130,1,''),
        (14,'halflife','','cheated','','/^Secure: \"(.+(?:<[^>]*>))\" was detected cheating/',140,0,''),
        (15,'halflife','','ban','','/^(Addip|Ban(?:id)?): \"([^\"]+)\" was (?:kicked and )?(?:banned)(?: by IP)? \"([^\"]+)\" by \"([^\"]+)\"(.*)/',150,1,''),
        (16,'halflife','','unban','','/^Remove(id|ip): \"([^\"]+)\" was unbanned by \"(.+(?:<[^>]*>))\"(.*)/',160,1,''),
        (17,'halflife','','kick','','/^Kick: \"(.+(?:<[^>]*>))\" was kicked by \"(.+(?:<[^>]*>)?)\"(.*)/',170,0,''),
        (18,'halflife','','pingkick','','/^\"(.+(?:<[^>]*>))\" kicked due to high ping(.*)/',180,0,''),
        (19,'halflife','','ffkick','','/^\"(.+(?:<[^>]*>))\" has been auto kicked from the game for TKing/',190,0,''),
        (20,'halflife','','startedmap','','/^(Started|Loading) map \"([^\"]+)\"(.*)/',200,0,''),
        (21,'halflife','','logstartend','','/^Log file (started|closed)(.*)/',210,0,''),
        (22,'halflife','','ignored1','','/^[Ss]erver (?:cvars?|say|shutdown)/',220,1,''),
        (23,'halflife','','ignored2','','/^(?:\\]TSC\\[|Succeeded|FATAL|-|Loaded)/',230,1,''),
        (24,'halflife','','ignored3','','/^(?:Config|Swear|server_)/',240,1,''),
        (25,'halflife','','ignored4','','/^\"[^\"]+\" = \"/',250,1,''),
        (30,'halflife','dod','plrtrigger','','/^\"(.+(?:<[^>]*>))\" triggered(?: a)? \"([^\"]+)\"(.*)/',300,0,''),
        (33,'halflife','','changed_role','','/^\"(.+(?:<[^>]*>))\" changed role to \"([^\"]+)\"/',330,0,''),
        (34,'halflife','dod','dod_objitem','','/^\"(.+(?:<[^>]*>))\" triggered an objective item/',340,1,''),
        (35,'halflife','dod','dod_teamscore','','/^\"([^\"]+)\" scored \"([^\"]+)\" with \"([^\"]+)\" players/',350,0,''),
        (36,'halflife','dod','teamtrigger','','/^Team \"([^\"]+)\" triggered(?: a)? \"([^\"]+)\"(.*)/',360,0,''),
        (37,'halflife','dod','dod_ignore1','','/^(?:Final)/',370,1,''),
        (45,'halflife','','rcon2','','/^rcon from/',130,1,''),
        (48,'halflife','','spatial','','/^\\[KTRAJ\\] \"(.+(?:<[^>]*>))\" killed \"(.+(?:<[^>]*>))\" with \"([^\"]*)\"(.*)/',480,0,''),
        (49,'halflife','','plugin','','/^\\[[^\\]]+\\]/',490,1,''),
        (50,'halflife','','console','','/^(CONSOLE|PLAYER FILTER) :/',500,1,''),
        (100,'halflife','','ignored5','','/^Server name is \"([^"]+)\"/',1000,1,''),
        (101,'halflife','','ignored6','','/^Connection to Steam servers successful./',1010,1,''),
        (102,'halflife','','ignored7','','/^VAC secure mode is activated./',1020,1,''),
        (103,'halflife','','ignored8','','/^Assigned anonymous gameserver Steam ID \[(.:\\d:\\d+:\\d+)\]./',1030,1,''),
        (104,'halflife','','ignored9','','/^Public IP is ([0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4}|(\\d{1,3}\.){3}\\d{1,3}./',1040,1,'');

INSERT INTO `ps_config_plrbonuses` (`id`, `eventname`, `enactor`, `enactor_team`, `victim`, `victim_team`, `description`, `gametype`, `modtype`) 
    VALUES 
        (15,'bomb_defuse',2,1,-1,0,'A player defused a bomb','halflife','dod'),
        (16,'bomb_plant',2,1,0,0,'A player planted a bomb','halflife','dod'),
        (17,'dod_blocked_point',1,0,0,0,'1 or more players blocked a control point before it could be captured from the enemy team.','halflife','dod'),
        (18,'dod_capture_area',2,0,0,0,'1 or more players captured a flag area','halflife','dod'),
        (19,'dod_control_point',2,0,0,0,'A Player captured a flag point','halflife','dod'),
        (20,'kill_planter',5,0,0,0,'A player killed a player while they were attempting to plant a bomb.','halflife','dod'),
        (34,'ffkill',-10,0,0,0,'when a player kills a team mate','','');

INSERT INTO `ps_config_awards` (`id`, `enabled`, `idx`, `type`, `negative`, `class`, `name`, `groupname`, `phrase`, `expr`, `order`, `where`, `limit`, `format`, `gametype`, `modtype`, `rankedonly`, `description`) 
    VALUES 
        (4,1,10,'player',0,'','Highest Skill','','{$player.link} has the highest skill with {$award.value}','{$skill}','desc','',0,'%.02f',NULL,NULL,1,'Player with the highest skill'),
        (6,1,20,'player',0,'','Most Kills','','{$player.link} has killed the most players ({$award.value})','{$kills}','desc','',0,'commify',NULL,NULL,1,'Player with the most kills (any team)'),
        (8,1,70,'player',0,'','Most Time Online','','{$player.link} has been online the longest ({$award.value})','{$onlinetime}','desc','',25,'compacttime',NULL,NULL,1,'Player with the most online time'),
        (9,1,190,'weaponclass',0,'','Most Kills with {$weapon.class} weapons','','{$player.link} has the most {$weapon.class} kills ({$award.value})','{$kills}','desc','',0,'commify',NULL,NULL,1,'Most kills with {$weapon.class} type weapons (including: {$weapon.list}).'),
        (10,1,180,'weapon',0,'','Most Kills with {$weapon.name}','','{$player.link} has the most {$weapon.link} kills ({$award.value})','{$kills}','desc','',0,'commify',NULL,NULL,1,'Most kills with a {$weapon.name}'),
        (13,1,30,'player',0,'','Most Bonus Points','','{$player.link} achieved the most bonus points ({$award.value})','{$totalbonus}','desc','',25,'commify',NULL,NULL,1,'Player that has achieved the most bonus points.'),
        (17,1,165,'player',0,'','Most Allied Flags Captured','','{$player.link} has the most Allied flag captures ({$award.value} flags)','{$alliesflagscaptured}','desc','',10,'commify','halflife','dod',1,'Most flags captured as an ally.'),
        (19,1,170,'player',0,'','Most Axis Flags Captured','','{$player.link} has the most Axis flag captures ({$award.value} flags)','{$axisflagscaptured}','desc','',10,'commify','halflife','dod',1,'Most flags captured as an Axis.'),
        (22,1,140,'player',0,'','Most Flags Captured','','{$player.link} has captured the most flags ({$award.value})','{$flagscaptured}','desc','',10,'commify','halflife','dod',1,'Player has captured the most flags.'),
        (23,1,50,'player',1,'','Worst Teammate','','{$player.link} has killed the most teammates ({$award.value})','{$ffkills}','desc','',0,'commify',NULL,NULL,1,'Player with the most friendly fire kills (ie: Worst Teammate)'),
        (25,1,60,'player',1,'','Worst Team Kill Percentage','','{$player.link} has the highest team kill percentage ({$award.value})','{$ffkills} / {$kills} * 100','desc','',0,'%0.02f%%',NULL,NULL,1,'Player with the highest team kill percentage.');

INSERT INTO `ps_config_overlays` (`id`, `gametype`, `modtype`, `map`, `minx`, `miny`, `maxx`, `maxy`, `width`, `height`, `flipv`, `fliph`, `rotate`) 
    VALUES 
        (58, 'halflife', 'dod', 'dod_acclaim', -1920, -3456, 2560, 3584, 589, 941, 1, 0, 0),
        (59, 'halflife', 'dod', 'dod_advance', -1152, -3968, 2176, 3968, 589, 941, 1, 0, 0),
        (60, 'halflife', 'dod', 'dod_dummy', 1472, -3968, -2176, 4032, 460, 1015, 1, 0, 0),
        (61, 'halflife', 'dod', 'dod_edge2', -2176, -3968, 1472, 4032, 460, 1015, 1, 0, 0),
        (62, 'halflife', 'dod', 'dod_expire_b3', -3840, -1508, 3608, 1124, 1005, 354, 1, 0, 0),
        (63, 'halflife', 'dod', 'dod_freeze_b5', -2112, -1024, 3648, 3584, 876, 704, 1, 0, 0),
        (64, 'halflife', 'dod', 'dod_frost2', -3326, -2562, 3076, 3348, 799, 735, 1, 0, 0),
        (65, 'halflife', 'dod', 'dod_fury', -2048, -2240, 2176, 2816, 679, 785, 1, 0, 0),
        (66, 'halflife', 'dod', 'dod_muhle_b2', -3978, -2054, 1872, 1890, 871, 585, 1, 0, 0),
        (67, 'halflife', 'dod', 'dod_siracusa', -1216, -2304, 2560, 2496, 589, 742, 1, 0, 0),
        (68, 'halflife', 'dod', 'dod_snowcity_v3', -3484, -3646, 3454, 318, 989, 565, 1, 0, 0),
        (69, 'halflife', 'dod', 'dod_steinburg', -3264, -2560, 1088, 3136, 629, 818, 1, 0, 0),
        (70, 'halflife', 'dod', 'dod_strom_b4', -2674, -2128, 2760, 2458, 943, 797, 1, 0, 0),
        (71, 'halflife', 'dod', 'dod_tact_v5', -1728, -3200, 3392, 640, 819, 618, 1, 0, 0),
        (72, 'halflife', 'dod', 'dod_thunder', -3968, -3840, 3840, 2304, 974, 760, 1, 0, 0),
        (73, 'halflife', 'dod', 'dod_vire', -1168, -3456, 2560, 528, 699, 746, 1, 0, 0);
        
INSERT INTO `ps_config` (`id`, `conftype`, `section`, `var`, `value`, `label`, `type`, `locked`, `verifycodes`, `options`, `help`) 
    VALUES 
        (1,'main',NULL,'meta_keywords','PsychoStats Game Server Player Statistics Day of Defeat DOD Valve','Site HTML Meta Key Words','text',0,'','','These are the HTML meta key words for your PsychoStats.  They are used by search engines to provide search results.');
